CREATE TABLE IF NOT EXISTS model_summaries (
  slug                         TEXT PRIMARY KEY,
  label                        TEXT NOT NULL,
  json_validity_mean           REAL NOT NULL,
  json_validity_ci_lower       REAL NOT NULL,
  json_validity_ci_upper       REAL NOT NULL,
  intent_accuracy_mean         REAL NOT NULL,
  intent_accuracy_ci_lower     REAL NOT NULL,
  intent_accuracy_ci_upper     REAL NOT NULL,
  gatekeeper_accuracy_mean     REAL NOT NULL,
  gatekeeper_accuracy_ci_lower REAL NOT NULL,
  gatekeeper_accuracy_ci_upper REAL NOT NULL,
  slot_f1_mean                 REAL NOT NULL,
  slot_f1_ci_lower             REAL NOT NULL,
  slot_f1_ci_upper             REAL NOT NULL,
  hallucination_rate_mean      REAL NOT NULL,
  hallucination_rate_ci_lower  REAL NOT NULL,
  hallucination_rate_ci_upper  REAL NOT NULL,
  judge_score_mean             REAL NOT NULL,
  judge_score_ci_lower         REAL NOT NULL,
  judge_score_ci_upper         REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS eval_rows (
  id                    SERIAL PRIMARY KEY,
  seed_id               TEXT NOT NULL,
  model_slug            TEXT NOT NULL,
  synthetic_message     TEXT,
  gt_intent_action      TEXT,
  gt_gatekeeper_status  TEXT,
  gt_order_id           TEXT,
  gt_invoice_id         TEXT,
  json_valid            BOOLEAN,
  pred_intent_action    TEXT,
  pred_gatekeeper_status TEXT,
  pred_order_id         TEXT,
  pred_invoice_id       TEXT,
  intent_correct        BOOLEAN,
  gatekeeper_correct    BOOLEAN,
  slot_f1               REAL,
  hallucinated_slots    BOOLEAN,
  judge_score           INTEGER,
  judge_reason          TEXT,
  UNIQUE(seed_id, model_slug)
);
